from __future__ import annotations

from typing import Any


def get_call_stats() -> dict[str, int]: ...
def reset_call_stats() -> None: ...
def backend_status(backend: str = ..., device: str = ...) -> dict[str, Any]: ...
